name: polymer_app_layout_template
version: 0.0.13
description: Polymer application template with responsive Material Design and routing
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/polymer-app-layout-templates

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc.6"
  polymer_elements: "^1.0.0-rc.3"
  route_hierarchical: "^0.6.0"
  web_components: ^0.12.0
  browser: ^0.10.0
  reflectable: ^0.3.1
  polymer_include_element: "^0.0.5"
transformers:
- web_components:
    entry_points:
    - demo/index.html
- reflectable:
    entry_points:
    - demo/index.dart
- $dart2js:
    minify: true
