name: polymer_app_layout_template
version: 0.0.1
description: Port of polymer-app-layout-template js to dart
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/polymer-app-layout-templates

dependencies:
  polymer: "^1.0.0-rc.2"
  polymer_elements: "^1.0.0-rc.1"
  route_hierarchical: "^0.6.0"
  web_components: ^0.12.0
  browser: ^0.10.0
  reflectable: ^0.3.1
transformers:
- web_components:
    entry_points:
    - test/nav-view/index.html
- reflectable:
    entry_points:
    - test/nav-view/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
